### ISSUE TITLE
Change simple queries to a more secure method (like prepared queries)

### ISSUE THREAD

**Issue by zzzzz1st** [zzzzz1st/CalosiLicenses#1]
### Security Problem

I want to change simple queries to a more secure way in order to protect code from SQL injection vulnerability. You can ask me for more clarifications.

**Comment by mohannaidu** [comment]
you can protect yourself using parameters binding. would you like me to have a go at it?

**Comment by zzzzz1st** [comment]
Yes of course you can. That’s a nice method. If you want to test it you can create tables locally. If you want more informations about the tables feel free to ask me.
